### ISSUE TITLE
Zero width patterns

### ISSUE THREAD

**Issue by rgrinberg** [google/redgrep#1]
E.g. stuff like:

```
pat(?=xxx)
pat(?!yyy)
```

I assume these should be possibly with the current DFA engine with some restrictions on the patterns (e.g. width must be bounded, no grouping) but correct me I'm wrong.

**Comment by junyer** [comment]
As long as you can express the requirements in terms of sets of strings, you can use conjunction and complement to achieve a similar effect. redgrep actually implements `[^abc]` as `![abc]&.`, for example, because it's the intersection of the set of strings that are not `a`, `b` or `c` and the set of strings that are single characters.
